---
title: "ADS503-02-SP22 - Final Project: Team 3"
author: "Carr_Aaron"
date: "06/27/2022"
output:
  pdf_document: default
  html_document:
    df_print: paged
header-includes:
- \usepackage{fvextra}
- \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
- \usepackage{pdflscape}
- \newcommand{\blandscape}{\begin{landscape}}
- \newcommand{\elandscape}{\end{landscape}}
---

## RMarkdown global setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r global.options, include=TRUE}
knitr::opts_chunk$set(
  fig.align = 'center'
  )
```

```{r lib, message=FALSE}
library(AppliedPredictiveModeling)
library(BioStatR)
library(car)
library(caret)
library(class)
library(corrplot)
library(datasets)
library(dplyr)
library(e1071)
library(Hmisc)
library(mlbench)
library(ggplot2)
library(gridExtra)
library(psych)
library(randomForest)
library(RANN)
library(rpart)
library(rpart.plot)
library(scales)
```

## Create function to generate boxplots for continuous variables
```{r, fig.height=10, fig.width=10}
# Define function to produce formatted boxplots
box_comp <- function(xcol = c(), df = NA) {
  sig <- 3
  metrics_df01 <- data.frame(metric = c("",
                                        "Total N:",
                                        "Count",
                                        "NA Count",
                                        "Mean",
                                        "Median",
                                        "Mode",
                                        "Standard Deviation",
                                        "Variance",
                                        "Range",
                                        "Min",
                                        "Max",
                                        "IQR Outlier Limit",
                                        "25th Percentile",
                                        "75th Percentile",
                                        "Lower Outlier Threshold",
                                        "Upper Outlier Threshold",
                                        "Subset w/o Outliers:",
                                        "Count",
                                        "%",
                                        "Outlier %",
                                        "NA Count",
                                        "Mean",
                                        "Median",
                                        "Mode",
                                        "Standard Deviation",
                                        "Variance",
                                        "Range",
                                        "Min",
                                        "Max"
                                        ))
  for (var in xcol) {
    df_s1 <- df[, var]
    df_s1s1 <-data.frame(df_s1)
    df_s1_fit <- preProcess(df_s1s1,
                            method = c("center", "scale"))
    df_s1_trans <- predict(df_s1_fit, df_s1s1)
    

    # Calculate quartiles
    var_iqr_lim <- IQR(df_s1) * 1.5
    var_q1 <- quantile(df_s1, probs = c(.25))
    var_otlow <- var_q1 - var_iqr_lim
    var_q3 <- quantile(df_s1, probs = c(.75))
    var_othigh <- var_q3 + var_iqr_lim
    
    # Subset non-outlier data 
    var_iqr_df01 <- subset(df, (abs(df_s1_trans) < 3))
    #var_iqr_df01 <- subset(df, (df_s1 > var_otlow & df_s1 < var_othigh))
    df_s2 <- var_iqr_df01[, var]

    # Begin calculating measures of centrality & dispersion
    var_mean <- mean(df_s1)
    var_iqr_df01_trunc_mean <- mean(df_s2)
    var_med <- median(df_s1)
    var_iqr_df01_trunc_med <- median(df_s2)
    var_mode <- mode(df_s1)
    var_iqr_df01_trunc_mode <- mode(df_s2)
    var_stde <- sd(df_s1)
    var_iqr_df01_trunc_stde <- sd(df_s2)
    var_vari <- var(df_s1)
    var_iqr_df01_trunc_vari <- var(df_s2)
    var01_min <- min(df[, var])
    var01_max <- max(df[, var])
    var01_range <- var01_max - var01_min
    var02_min <- min(var_iqr_df01[, var])
    var02_max <- max(var_iqr_df01[, var])
    var02_range <- var02_max - var02_min
    
    # Configure y-axis min & max to sync graphs
    plot_min <- min(var01_min, var02_min)
    plot_max <- max(var01_max, var02_max)
    nonoutlier_perc <- round((as.numeric(dim(var_iqr_df01)[1] / as.numeric(dim(df)[1]))) * 100, 1)
    measure_val01 <- c(paste0("Variable: ", var),
                       "",
                       as.character(dim(df)[1]),
                       sum(is.na(df_s1)),
                       round(var_mean, sig),
                       round(var_med, sig),
                       var_mode,
                       round(var_stde, sig),
                       round(var_vari, sig),
                       round(var01_range, sig),
                       round(var01_min, sig),
                       round(var01_max, sig),
                       paste0("+/-", round(var_iqr_lim, sig)),
                       round(var_q1, sig),
                       round(var_q3, sig),
                       round(var_otlow, sig),
                       round(var_othigh, sig),
                       "",
                       as.character(dim(var_iqr_df01)[1]),
                       paste0(nonoutlier_perc, "%"),
                       paste0(100 - nonoutlier_perc, "%"),
                       sum(is.na(df_s2)),
                       round(var_iqr_df01_trunc_mean, sig),
                       round(var_iqr_df01_trunc_med, sig),
                       var_iqr_df01_trunc_mode,
                       round(var_iqr_df01_trunc_stde, sig),
                       round(var_iqr_df01_trunc_vari, sig),
                       round(var02_range, sig),
                       round(var02_min, sig),
                       round(var02_max, sig)
                       )
    
    var_name <- paste0("Variable: ", var)
    metrics_df01[, ncol(metrics_df01) + 1] <- measure_val01
}
  print(metrics_df01)
  boxplot(df)
  return(metrics_df01)
}
```

## Importing Train/Test Datasets
```{r}
biodeg_train_x01_df01 <- read.csv("../data/biodeg_train.csv", header = TRUE, sep = ",")
biodeg_test_x01_df01 <- read.csv("../data/biodeg_test.csv", header = TRUE, sep = ",")

biodeg_train_y01_df01 <- read.csv("../data/response_train.csv", header = TRUE, sep = ",")
biodeg_test_y01_df01 <- read.csv("../data/response_test.csv", header = TRUE, sep = ",")

biodeg_train_y01_vc01 <- biodeg_train_y01_df01[["x"]]
biodeg_test_y01_vc01 <- biodeg_test_y01_df01[["x"]]
```

## Run function to create comparative boxplots
```{r}
biodeg_train_x01_df01_cols01 <- colnames(biodeg_train_x01_df01)
biodeg_train_x01_df01_metrics <- box_comp(xcol = biodeg_train_x01_df01_cols01, df = biodeg_train_x01_df01)
write.csv(biodeg_train_x01_df01_metrics,"../outputs/demos.csv", row.names = FALSE)

biodeg_train_x02_lst01 = biodeg_train_x01_df01_cols01[8]
biodeg_train_x02_df01 <- subset(x = biodeg_train_x01_df01, select = biodeg_train_x02_lst01)
box_comp(xcol = biodeg_train_x02_lst01, df = biodeg_train_x02_df01)

biodeg_train_x03_lst01 = biodeg_train_x01_df01_cols01[-8]
biodeg_train_x03_df01 <- subset(x = biodeg_train_x01_df01, select = biodeg_train_x03_lst01)
box_comp(xcol = biodeg_train_x03_lst01, df = biodeg_train_x03_df01)

biodeg_train_x04_lst01 = biodeg_train_x01_df01_cols01[23]
biodeg_train_x04_df01 <- subset(x = biodeg_train_x01_df01, select = biodeg_train_x04_lst01)
box_comp(xcol = biodeg_train_x04_lst01, df = biodeg_train_x04_df01)

biodeg_train_x05_lst01 = biodeg_train_x03_lst01[-22]
biodeg_train_x05_df01 <- subset(x = biodeg_train_x01_df01, select = biodeg_train_x05_lst01)
box_comp(xcol = biodeg_train_x05_lst01, df = biodeg_train_x05_df01)
```
```{r}
biodeg_x01_df01_train_fit01 <- preProcess(biodeg_train_x01_df01,
                                          method = c("center", "scale"))

biodeg_train_x01_trans_df01 <- predict(biodeg_x01_df01_train_fit01, biodeg_train_x01_df01)
sapply(biodeg_train_x01_trans_df01, function(x) sum(abs(x) > 3))
```
