---
title: "1.0-sk-lda"
author: "Sreeja K"
date: "`r Sys.Date()`"
output: word_document
---


```{r}
library(caret)
library(pROC)
set.seed(100)
```


```{r}
biodeg_train <- read.csv("C:/Users/kurap/OneDrive/Documents/GitHub/predictive-modeling/data/biodeg_train.csv", header = TRUE, sep = ",")
biodeg_test <- read.csv("C:/Users/kurap/OneDrive/Documents/GitHub/predictive-modeling/data/biodeg_test.csv", header = TRUE, sep = ",")

response_train <- read.csv("C:/Users/kurap/OneDrive/Documents/GitHub/predictive-modeling/data/response_train.csv", header = TRUE, sep = ",")
response_test <- read.csv("C:/Users/kurap/OneDrive/Documents/GitHub/predictive-modeling/data/response_test.csv", header = TRUE, sep = ",")

response_train <- as.factor(as.matrix(response_train))
response_test <- as.factor(as.matrix(response_test))

y_pred_test <- read.csv("C:/Users/kurap/OneDrive/Documents/GitHub/predictive-modeling/data/test-results/y_pred.csv", header = TRUE, sep = ",")
y_pred_test <- lapply(y_pred_test, function(x) (as.factor(x)))
```

```{r }
set.seed(100)
ctrl <- trainControl(method = "repeatedcv", repeats = 5, classProbs = TRUE)
lda_fit = train(x=biodeg_train, y = response_train, method = "lda", preProc = c("center", "scale"), metric = "ROC", trControl = ctrl)

lda_Pred  = predict(lda_fit,biodeg_train, type = "prob") 
lda_ROC = pROC::roc(response = response_train, predictor = lda_Pred[, 1])

lda_AUC = lda_ROC$auc[1]
lda = list(classifier = lda_fit, predictions = lda_Pred, roc = lda_ROC, auc = lda_AUC)

```

```{r}
Test_Op <- data.frame(obs = response_test,NSC = predict(lda_fit, biodeg_test))
confusionMatrix(Test_Op$NSC, Test_Op$obs, positive = "RB")
plot(lda_ROC, legacy.axes = TRUE)
```