---
title: "ADS503-02-SP22 - Final Project: Team 3"
author: "Carr_Aaron"
date: "06/27/2022"
output:
  pdf_document: default
  html_document:
    df_print: paged
header-includes:
- \usepackage{fvextra}
- \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
- \usepackage{pdflscape}
- \newcommand{\blandscape}{\begin{landscape}}
- \newcommand{\elandscape}{\end{landscape}}
---

## RMarkdown global setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r global.options, include=TRUE}
knitr::opts_chunk$set(
  fig.align = 'center'
  )
```

```{r lib, message=FALSE}
library(AppliedPredictiveModeling)
library(BioStatR)
library(car)
library(caret)
library(class)
library(corrplot)
library(datasets)
library(dplyr)
library(e1071)
library(Hmisc)
library(mlbench)
library(ggplot2)
library(gridExtra)
library(psych)
library(randomForest)
library(RANN)
library(rpart)
library(rpart.plot)
library(scales)
```

## Importing Train/Test Datasets
```{r}
biodeg_train_x01_df01 <- read.csv("../data/biodeg_train.csv", header = TRUE, sep = ",")
biodeg_test_x01_df01 <- read.csv("../data/biodeg_test.csv", header = TRUE, sep = ",")

biodeg_train_y01_df01 <- read.csv("../data/response_train.csv", header = TRUE, sep = ",")
biodeg_test_y01_df01 <- read.csv("../data/response_test.csv", header = TRUE, sep = ",")

biodeg_train_y01_vc01 <- biodeg_train_y01_df01[["x"]]
biodeg_test_y01_vc01 <- biodeg_test_y01_df01[["x"]]
```

```{r, fig.height=8, fig.width=10}
set.seed(100)
biodeg_x01_df01_train_fit01 <- preProcess(biodeg_train_x01_df01,
                                          method = c("BoxCox", "center", "scale", "nzv", "spatialSign"))
biodeg_x01_df01_train_fit01

# Transform training set
biodeg_train_x01_trans_df01 <- predict(biodeg_x01_df01_train_fit01, biodeg_train_x01_df01)
head(biodeg_train_x01_trans_df01, 5)
hist.data.frame(biodeg_train_x01_trans_df01)

# Transform test set using training set-based fit
biodeg_test_x01_trans_df01 <- predict(biodeg_x01_df01_train_fit01, biodeg_test_x01_df01)
head(biodeg_test_x01_trans_df01, 5)
```

```{r}
write.csv(biodeg_train_x01_trans_df01,"../data/biodeg_train_trans.csv", row.names = FALSE)
write.csv(biodeg_test_x01_trans_df01,"../data/biodeg_test_trans.csv", row.names = FALSE)
```
