---
title: "K Nearest Neighbor Model"
output: html_document
author: "Ivan A Chavez"
---
```{r}
# Loading packages and setting seed
library(caret)
library(pROC)
set.seed(100)
```
```{r}
# Loading transformed data to perform modeling
biodeg_train <- read.csv("../data/biodeg_train.csv", header = TRUE, sep = ",")
biodeg_test <- read.csv("../data/biodeg_test.csv", header = TRUE, sep = ",")
response_train <- read.csv("../data/response_train.csv", header = TRUE, sep = ",")
response_test <- read.csv("../data/response_test.csv", header = TRUE, sep = ",")

response_train <- as.factor(as.matrix(response_train))
response_test <- as.factor(as.matrix(response_test))

# Pulling test outcome data to add results and transforming each coulmn to a factor
y_pred_test <- read.csv("../data/test-results/05-06_y_pred.csv", header = TRUE, sep = ",")
y_pred_test <- lapply(y_pred_test, function(x) (as.factor(x)))

```
```{r}

ctrl <- trainControl(method = "repeatedcv",
                     repeats = 5,
                     summaryFunction = twoClassSummary,
                     classProbs = TRUE,
                     savePredictions = TRUE)

knnFit <- train(x = biodeg_train, y = response_train,
                 method = "knn",
                 tuneGrid = data.frame(k = 1:20),
                 preProcess = c("nzv", "center", "scale"),
                 metric = "ROC",
                 trControl = ctrl)

#knnFit

y_pred_test$knn <- predict(knnFit, biodeg_test)

# Accuracy: 0.8429 Sn: 0.7887  Sp: 0.8705
confusionMatrix(y_pred_test$knn, y_pred_test$obs, positive = "RB")

#nscCM <- confusionMatrix(nscFit, norm = "none")
#nscCM

## Plot the ROC curve for the hold-out set
knnRoc <- roc(response = knnFit$pred$obs,
              predictor = knnFit$pred$RB,
              levels = rev(levels(knnFit$pred$obs)))

plot(knnRoc, legacy.axes = TRUE)
#nscRoc$auc
```
```{r}

biodeg_train_uni <- read.csv("../data/univariate-selection-data/biodeg_train_univariate.csv", header = TRUE, sep = ",")
biodeg_test_uni <- read.csv("../data/univariate-selection-data/biodeg_test_univariate.csv", header = TRUE, sep = ",")
```
```{r}

set.seed(100)

ctrl <- trainControl(method = "repeatedcv",
                     repeats = 5,
                     summaryFunction = twoClassSummary,
                     classProbs = TRUE,
                     savePredictions = TRUE)

knnFit <- train(x = biodeg_train_uni, y = response_train,
                method = "knn",
                tuneGrid = data.frame(k = 1:20),
                preProcess = c("nzv", "center", "scale"),
                metric = "ROC",
                trControl = ctrl)

#knnFit

y_pred_test$knn_uni <- predict(knnFit, biodeg_test_uni)

# Accuracy: 0.9014 Sn: 0.9014  Sp: 0.9281
confusionMatrix(y_pred_test$knn_uni, y_pred_test$obs, positive = "RB")

## Plot the ROC curve for the hold-out set
knnRoc <- roc(response = knnFit$pred$obs,
              predictor = knnFit$pred$RB,
              levels = rev(levels(knnFit$pred$obs)))

plot(knnRoc, legacy.axes = TRUE)
#nscRoc$auc
```
```{r}

write.csv(y_pred_test,"../data/test-results/y_pred.csv", row.names = FALSE)
```
