---
title: "1.0-sk-scatterplots"
author: "Sreeja K"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(caret)
library(tidyverse)
library(ggplot2)
library(GGally)
set.seed(100)
```



```{r}
names <- c("SpMax_L", "J_Dz(e)", "nHM", "F01[N-N]", "F04[C-N]", "NssssC", "nCb-", "C%", "nCp", "nO", "F03[C-N]", "SdssC", "HyWi_B(m)", "LOC", "SM6_L", "F03[C-O]", "Me", "Mi", "nN-N", "nArNO2", "nCRX3", "SpPosA_B(p)", "nCIR", "B01[C-Br]", "B03[C-Cl]", "N-073", "SpMax_A", "Psi_i_1d", "B04[C-Br]", "SdO", "TI2_L", "nCrt", "C-026", "F02[C-N]", "nHDon", "SpMax_B(m)", "Psi_i_A", "nN", "SM6_B(m)", "nArCOOR", "nX", "experimental class")

biodeg <- read.csv("C:/Users/kurap/OneDrive/Documents/GitHub/predictive-modeling/data/biodeg.csv", header = FALSE, sep = ";", col.names = names)

```

```{r}

index_biodeg <- createDataPartition(biodeg$experimental.class, p=.80, list = FALSE)
biodeg_trainset <- biodeg[index_biodeg,]
biodeg_testset <- biodeg[-index_biodeg,]

response_train <- biodeg_trainset[,42]
response_test <- biodeg_testset[,42]

biodeg_train <- biodeg_trainset[,-42]
biodeg_test <- biodeg_testset[,-42]
```

```{r}
ggplot(biodeg_trainset, aes(x = SpMax_L, y = nX)) + geom_point()
```

```{r}
#Scatterplot matrix
'par("mar")
par(mar=c(1,1,1,1))'

pairs(biodeg_trainset[1:6])
```

```{r}
pairs(biodeg_trainset[7:12])
```

```{r}
pairs(biodeg_trainset[13:20])
```

```{r}
pairs(biodeg_trainset[21:27])
```

```{r}
pairs(biodeg_trainset[28:33])
```

```{r}
pairs(biodeg_trainset[34:37])
```

```{r}
pairs(biodeg_trainset[38:41])
```